# Generated by Django 3.2.16 on 2025-01-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250127_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={
                'ordering': ('created_at',),
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии'
            },
        ),
    ]
